### ISSUE TITLE
#awsadminmfa - AWS Administrative accounts don't require MFA

### ISSUE THREAD

**Issue by tinnightcap** [Nubisproject/nubis-docs#127]
_From @gozer on August 24, 2015 17:33_

From https://mana.mozilla.org/wiki/display/SECURITY/Nubis#Nubis-#awsadminmfa

AWS Administrative accounts don't require MFA

The dev automation team member non-federated user accounts in the stage and prod AWS nubis accounts are not required to have MFA enabled by policy. A compromise of one of these accounts would affect all production products.

Recommendations :

Establish a policy requiring MFA on administrative accounts

_Copied from original issue: nubisproject/nubis-meta#19_

**Comment by tinnightcap** [comment]
This is required as per the document here:

https://mana.mozilla.org/wiki/display/EA/Standards+and+Processes

MFA has been enabled for all admins on all accounts.

**Comment by tinnightcap** [comment]
_From @gdestuynder on September 18, 2015 18:16_

@tinnightcap is this also required (ie accounts can't be used without MFA) or voluntarily following policy document?

If the later, have we audited all current accounts MFA?
If MFA cannot be enforced - do we have an audit process to ensure MFA is always in use?

**Comment by tinnightcap** [comment]
_From @gdestuynder on September 18, 2015 18:55_

we discussed this on vidyo:
since we can't enforce it at the AWS level for practical reasons, we need to activate securitymonkey for the account to do the auditing

**Comment by tinnightcap** [comment]
_From @gozer on September 18, 2015 21:9_

Activate security monkey? Does that mean that we have security monkey up and running somewhere already!?

Or are we talking about deploying, running and managing our own security monkey infrastructure?

**Comment by tinnightcap** [comment]
_From @gdestuynder on September 18, 2015 23:58_

@gene1wood ^^

**Comment by tinnightcap** [comment]
_From @gene1wood on September 19, 2015 18:44_

Opsec runs a customized instance of Security Monkey which audits all Mozilla AWS accounts (except Cloud Services).

**Comment by tinnightcap** [comment]
_From @gdestuynder on September 23, 2015 17:38_

@gene1wood need to review row 28 #awsadminmfa after its enabled (from Nubis RR https://docs.google.com/spreadsheets/d/14-WS_GwB5xiy1xptLEKhgkwO4iNkMQLxpCS3oqmwbvs/edit#gid=1554391709)

**Comment by tinnightcap** [comment]
_From @gene1wood on October 13, 2016 23:35_

The security controls for this risk are being tracked in #22 as the technology involved affects both how admins use API keys and when MFA is and isn't required

**Comment by gene1wood** [comment]
It looks like these are copy pasted comments from nubisproject/nubis-meta#19 which now 404's. As a result some of these comments reference other nubis-meta issues (e.g. #22) which now point to nubis-docs PRs and issues (which aren't applicable).

**Comment by limed** [comment]
This is fixed, our deploy process now enforces us to have MFA tokens on every IAM account created
