### ISSUE TITLE
Problem running nubisproject/nubis-builder container

### ISSUE THREAD

**Issue by danielhartnell** [Nubisproject/nubis-docs#238]
Hey @tinnightcap,

I'm attempting to deploy a copy of Haul and wiki.mozilla.org to the nubis-training account for testing. Following the documentation here, I've been running into some errors:

https://github.com/nubisproject/nubis-docs/blob/develop/PREREQUISITES.md#run-the-nubis-builder-docker-image

```
vault-exec "${NUBIS_DOCKER[@]}" -e GIT_COMMIT_SHA=$(git rev-parse HEAD) nubisproject/nubis-builder:v0.7.0

Unable to find image 'nubisproject/nubis-builder:v0.7.0' locally
docker: Error response from daemon: manifest for nubisproject/nubis-builder:v0.7.0 not found.
See 'docker run --help'.
```

From there, I took a look on Docker Hub and I can see that v0.7.0 is not a tagged image. I went ahead and updated the command to pull v1.6.0 but now I'm receiving this error:

```
vault-exec "${NUBIS_DOCKER[@]}" -e GIT_COMMIT_SHA=$(git rev-parse HEAD) nubisproject/nubis-builder:v1.6.0
Unable to find image 'nubisproject/nubis-builder:v1.6.0' locally
v1.6.0: Pulling from nubisproject/nubis-builder
605ce1bd3f31: Already exists
500332dbea3a: Pull complete
41aa3c82719e: Pull complete
2212f5acdc7b: Pull complete
857341fd6910: Pull complete
d49c7793a843: Pull complete
86b9a6f6215e: Pull complete
c7a4b2974a5b: Pull complete
Digest: sha256:9e3fb15b425c4d6aeeb250cac4a9d5758dbb059a12a27ec96dcf150343a55655
Status: Downloaded newer image for nubisproject/nubis-builder:v1.6.0
Sourcing: /nubis/nubis-builder/bin/dependencies.sh
/nubis/build/nubis/builder/project.json not found
Build failed. Bailing out!
```

This also happens on the develop tag.

Can you help to resolve that so I can continue my testing? I'm happy to submit a PR to update the docs once we have the right image tag identified.

**Comment by danielhartnell** [comment]
I think that I should also mention that I did run the following prior to running `vault-exec`:

```
NUBIS_DOCKER=( 'docker' 'run' \
                '-u' "$UID:$(id -g)" \
                '--interactive' \
                '--tty' \
                '--env-file' "$(echo ~)/.docker_env" \
                '-v' "$PWD:/nubis/data" )
```

I'm wondering if the volume mapping there could be incorrect - assuming it's looking for project.json in my app's directory structure (Haul in this case).

**Comment by danielhartnell** [comment]
Ah, that appears to be related. Updating the volume mapping to `$PWD:/nubis/build` did not bail out immediately:

```
vault-exec "${NUBIS_DOCKER[@]}" -e GIT_COMMIT_SHA=$(git rev-parse HEAD) nubisproject/nubis-builder:v1.6.0
rsync: change_dir "/nubis/data" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1178) [sender=3.1.2]
Sourcing: /nubis/nubis-builder/bin/dependencies.sh
Loading: /nubis/nubis-builder/secrets/variables.json
Loading: /nubis/build/nubis/builder/project.json
Setting packer builders to: amazon-ebs-ubuntu
...
==> amazon-ebs-ubuntu: Error: name conflicts with an existing AMI: ami-ed328d95
Build 'amazon-ebs-ubuntu' errored: Error: name conflicts with an existing AMI: ami-ed328d95

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs-ubuntu: Error: name conflicts with an existing AMI: ami-ed328d95

==> Builds finished but no artifacts were created.
packer failed
Build failed. Bailing out!
```

I'll continue to troubleshoot.

**Comment by danielhartnell** [comment]
I made some changes in order to get a unique `GIT_COMMIT_SHA` value which should address the AMI name conflict (update - that did fix it).

In order to clear up the rsync error noted above, I ended up specifying two volumes in `NUBIS_DOCKER`. Does this seem like an appropriate response given the errors you see above? If so, I can submit a PR to the docs with this change:

```
NUBIS_DOCKER=( 'docker' 'run' \
                '-u' "$UID:$(id -g)" \
                '--interactive' \
                '--tty' \
                '--env-file' "$(echo ~)/.docker_env" \
                '-v' "$PWD:/nubis/data" \
                '-v' "$PWD:/nubis/build" )
```

**Comment by danielhartnell** [comment]
Please see the referenced issue as well. It felt unique enough to warrant a new GitHub issue in the relevant project.

**Comment by tinnightcap** [comment]
I missed your last update on this. That is not a good solution, that being adding the /nubis/build volume. That will cause you errors on your local file-system (files owned as root).

As to the issue you were seeing there, try using v1.7.0 of the nubis-builder container. I fixed that rsync error.

Also, if you wait till Thursday of this week, I will be presenting your team with a new tool that will make all of this a lot simpler and will deprecate that cheet-sheet entirely. I will also be updating the docs tomorrow to this new tooling.

I am going to close this out now, but do let me know if you run into any additional issues.
