### ISSUE TITLE
Document --debug tricks for Packer and nubis-builder

### ISSUE THREAD

**Issue by gozer** [Nubisproject/nubis-docs#45]
There are quite a few cool ways to speedup nubis development, and we need to document some of these tricks:
- nubis-builder --keep-json
- nubis-builder --debug
- nubis-builder --packer-option "--debug"

:clock1: 4h

**Comment by gozer** [comment]
Done in v2.0.0

**Comment by tinnightcap** [comment]
This is done as it is built into nubis-docker-builder and in the README.md
