### ISSUE TITLE
Create policy requiring peer review of code on projects hosted in Nubis

### ISSUE THREAD

**Issue by gene1wood** [Nubisproject/nubis-docs#73]
Due to the fact that for products hosted in Nubis, the application code will now also contain infrastructure code (CloudFormation templates) which will create infrastructure in AWS, we should require code reviews (at least of changes to infrastructure code).

Put together a policy doc that new products being onboarded into Nubis can reference to educate developers about this requirement in the Nubis environment.

**Comment by tinnightcap** [comment]
https://github.com/nubisproject/nubis-ci/issues/104 is a dupe of this issue but has more information, I will close this in favor of that issue
